#pragma once

#include <array>
#include <map>
#include <string_view>

enum opType {
    Null,
    Register,
    Address,
    Size,
    Offset,
    Comparison,
    Int8,
    Int16,
    Int32
};

const inline std::map<std::string_view, std::array<opType, 3>> opNames = {
    {"HLT",    { Null,     Null,     Null }},
    {"AND",    { Register, Register, Null }},
    {"ANDIB",  { Register, Int8,     Null }},
    {"ANDIW",  { Register, Int16,    Null }},
    {"ANDID",  { Register, Int32,    Null }},
    {"OR",     { Register, Register, Null }},
    {"ORIB",   { Register, Int8,     Null }},
    {"ORIW",   { Register, Int16,    Null }},
    {"ORID",   { Register, Int32,    Null }},
    {"NOT",    { Register, Null,     Null }},
    {"SHIL",   { Register, Register, Null }},
    {"SHILI",  { Register, Int8,     Null }},
    {"SHIR",   { Register, Register, Null }},
    {"SHIRI",  { Register, Int8,     Null }},
    {"ADD",    { Register, Register, Null }},
    {"ADDIB",  { Register, Int8,     Null }},
    {"ADDIW",  { Register, Int16,    Null }},
    {"ADDID",  { Register, Int32,    Null }},
    {"INCR",   { Register, Null,     Null }},
    {"DECR",   { Register, Null,     Null }},
    {"MUL",    { Register, Register, Null }},
    {"MULIB",  { Register, Int8,     Null }},
    {"MULIW",  { Register, Int16,    Null }},
    {"MULID",  { Register, Int32,    Null }},
    {"DIV",    { Register, Register, Null }},
    {"DIVIB",  { Register, Int8,     Null }},
    {"DIVIW",  { Register, Int16,    Null }},
    {"DIVID",  { Register, Int32,    Null }},
    {"MOD",    { Register, Register, Null }},
    {"MODIB",  { Register, Int8,     Null }},
    {"MODIW",  { Register, Int16,    Null }},
    {"MODID",  { Register, Int32,    Null }},
    {"CLEAR",  { Register, Null,     Null }},
    {"MOV1B",  { Register, Int8,     Null }},
    {"MOV2B",  { Register, Int8,     Null }},
    {"MOV3B",  { Register, Int8,     Null }},
    {"MOV4B",  { Register, Int8,     Null }},
    {"MOV1W",  { Register, Int16,    Null }},
    {"MOV2W",  { Register, Int16,    Null }},
    {"MOV3W",  { Register, Int16,    Null }},
    {"MOV4W",  { Register, Int16,    Null }},
    {"MOV1D",  { Register, Int32,    Null }},
    {"MOV2D",  { Register, Int32,    Null }},
    {"MOV3D",  { Register, Int32,    Null }},
    {"MOV4D",  { Register, Int32,    Null }},
    {"MOVR",   { Register, Register, Null }},
    {"SWAP",   { Register, Register, Null }},
    {"PUSH",   { Register, Null,     Null }},
    {"PUSHIB", { Int8,     Null,     Null }},
    {"PUSHIW", { Int16,    Null,     Null }},
    {"PUSHID", { Int32,    Null,     Null }},
    {"POP",    { Register, Null,     Null }},
    {"PEEK",   { Register, Null,     Null }},
    {"CMP",    { Register, Register, Comparison }},
    {"JMP",    { Offset,   Null,     Null }},
    {"JMPB",   { Int8,     Null,     Null }},
    {"JMPW",   { Int16,    Null,     Null }},
    {"JMPD",   { Int32,    Null,     Null }},
    {"CALL",   { Offset,   Null,     Null }},
    {"CALLB",  { Int8,     Null,     Null }},
    {"CALLW",  { Int16,    Null,     Null }},
    {"CALLD",  { Int32,    Null,     Null }},
    {"RET",    { Null,     Null,     Null }},
    {"WRT",    { Size,     Address,  Register }},
    {"READ",   { Register, Size,     Address }}
};
